version: '3.8'

services:
  app:
    container_name: lms
    image: python:3.9-slim
    ports:
      - "5000:5000"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file: .env # using .env file to load the environment variables except for MYSQL_HOST
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql


  mysql:
    container_name: lms-db
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./db/lms.sql:/docker-entrypoint-initdb.d/lms.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lms123
      MYSQL_DATABASE: lms

volumes:
  db-data: