version: '3.8'

services:
  app:
    container_name: lms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql            # Name of the MySQL service below
      FLASK_ENV: development
      DB_USER: lmsuser
      DB_PASSWORD: lms123
      DB_NAME: lms
      DB_PORT: 3306
    depends_on:
      - mysql

  mysql:
    container_name: lms-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lms
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lms123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/lms.sql:/docker-entrypoint-initdb.d/lms.sql:ro

volumes:
  db-data:
