version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lms
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lms123
    ports:
      - "3306:3306"

  app:
    image: umair81/app:latest
    container_name: lms-app
    depends_on:
      - mysql
    env_file: .env
    ports:
      - "5000:5000"
