apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  type: NodePort
  selector:
    app: library-management
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  - name: python-app
    port: 5000
    targetPort: 5000
    nodePort: 30000