name: CI Pipeline

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install dependencies
    - name: Install dependencies
      run: |  # Fixed: changed 'runs' to 'run'
        pip install -r requirements.txt

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Build Docker Images
    - name: Build Docker Images
      run: |  # Fixed: changed 'runs' to 'run'
        docker-compose up --build

    # 3. Test if containers start
    - name: Test containers
      run: |  # Fixed: changed 'runs' to 'run'
        docker-compose up -d
        docker-compose ps
        docker-compose down

    # 4. Manual Tagging and Push (Only on main branch push)
    - name: Tag and Push to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Login to Docker Hub
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
        # Get commit SHA (first 7 characters)
        COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        
        # Tag images with multiple tags
        docker tag your-app-image:latest ${{ secrets.DOCKER_USERNAME }}/library-app:latest
        docker tag your-app-image:latest ${{ secrets.DOCKER_USERNAME }}/library-app:$COMMIT_SHA
        docker tag your-app-image:latest ${{ secrets.DOCKER_USERNAME }}/library-app:${{ github.run_number }}
        
        # Tag MySQL image
        docker tag mysql:8.0 ${{ secrets.DOCKER_USERNAME }}/mysql-db:latest
        docker tag mysql:8.0 ${{ secrets.DOCKER_USERNAME }}/mysql-db:$COMMIT_SHA
        
        # Push all tagged images
        docker push ${{ secrets.DOCKER_USERNAME }}/library-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/library-app:$COMMIT_SHA
        docker push ${{ secrets.DOCKER_USERNAME }}/library-app:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mysql-db:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mysql-db:$COMMIT_SHA