name: Build and Push with Docker Compose

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate tag
      id: tag
      run: |
        COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)
        DATE=$(date +'%Y%m%d')
        echo "TAG=$DATE-$COMMIT_SHA_SHORT" >> $GITHUB_OUTPUT

    - name: Build and push with Docker Compose
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        # Build images
        docker-compose build
        
        # Tag with commit SHA
        docker tag ${DOCKER_USERNAME}/lms-app:latest ${DOCKER_USERNAME}/lms-app:${{ steps.tag.outputs.TAG }}
        
        # Push both tags
        docker push ${DOCKER_USERNAME}/lms-db:latest
        docker push ${DOCKER_USERNAME}/lms-db:${{ steps.tag.outputs.TAG }}
        
        echo "Images pushed:"
        echo "- ${DOCKER_USERNAME}/lms-db:latest"
        echo "- ${DOCKER_USERNAME}/lms-dbp:${{ steps.tag.outputs.TAG }}"