name: CI Pipeline
on:
  push:
    branches: [master]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create .env file
      run: |
        echo "FLASK_ENV=production" >> .env
        echo "DB_USER=lmsuser" >> .env
        echo "DB_PASSWORD=lms123" >> .env
        echo "DB_NAME=lms" >> .env
        echo "DB_PORT=3306" >> .env
        echo "MYSQL_HOST=mysql" >> .env
    
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build and Push app image
      run: |
        # Build the app service
        docker-compose build app
        
        # Get the actual image name created by docker-compose
        PROJECT_NAME=$(basename $(pwd) | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')
        BUILT_IMAGE="${PROJECT_NAME}_app:latest"
        
        # Tag with your Docker Hub username
        docker tag $BUILT_IMAGE ${{ secrets.DOCKER_USERNAME }}/app:latest
        docker tag $BUILT_IMAGE ${{ secrets.DOCKER_USERNAME }}/app:v2
        
        # Push both tags
        docker push ${{ secrets.DOCKER_USERNAME }}/app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/app:v2