name: CI Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # 3️⃣ Create .env file (needed by app service)
    - name: Create .env file
      run: |
        echo "FLASK_ENV=production" >> .env
        echo "DB_USER=lmsuser" >> .env
        echo "DB_PASSWORD=lms123" >> .env
        echo "DB_NAME=lms" >> .env
        echo "DB_PORT=3306" >> .env
        echo "MYSQL_HOST=mysql" >> .env

    # 4️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 5️⃣ Build Docker images from docker-compose
    - name: Build Docker images
      run: |
        docker-compose build

    # 6️⃣ Tag and Push both app & mysql images
    - name: Tag and Push images
      run: |
        for service in $(docker-compose config --services); do
          if [ "$service" = "mysql" ]; then
            echo "Skipping MySQL (official image)"
            continue
          fi

          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${service}
          echo "Tagging and pushing $IMAGE_NAME ..."

          docker tag ${service}:latest $IMAGE_NAME:latest
          docker tag ${service}:latest $IMAGE_NAME:v2

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:v2
        done
