name: CI Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # 3️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # ✅ Add .env file before build
    - name: Create .env file
      run: |
        echo "DB_USER=root" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_NAME=library" >> .env

    # 4️⃣ Build all images from docker-compose
    - name: Build Docker images
      run: |
        docker-compose build

    # 5️⃣ Tag and push all images with `latest` and `v2`
    - name: Tag and Push images
      run: |
        # List all built images
        docker images

        # Loop through each service defined in docker-compose
        for service in $(docker-compose config --services); do
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${service}
          
          echo "Tagging and pushing $IMAGE_NAME ..."
          
          # Tag images
          docker tag ${service}:latest $IMAGE_NAME:latest
          docker tag ${service}:latest $IMAGE_NAME:v2
          
          # Push both tags
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:v2
        done
